name: Build and Deploy to FTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
    - run: npm install
    - run: echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
    - run: npm run build
    - name: Make Asset Paths Relative
      run: |
        sed -i 's|href="/|href="./|g' dist/index.html
        sed -i 's|src="/|src="./|g' dist/index.html
    - name: Network Diagnostics
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
      run: |
        echo "Pinging $FTP_HOST..."
        ping -c 4 $FTP_HOST
        echo "Testing port 3000 on $FTP_HOST with nc..."
        nc -vz $FTP_HOST 3000
    - name: Upload to FTP
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_HOST: ${{ secrets.FTP_HOST }}
      run: |
        sudo apt-get -y install lftp
        lftp -d -u $FTP_USERNAME,$FTP_PASSWORD -p 3000 $FTP_HOST <<FTP_EOF
        set ftp:ssl-allow no
        # Deploy main app (dist folder)
        mkdir -p /apps.hereandnowai.com/apps/${{ github.event.repository.name }}
        mirror -R --delete --verbose ./dist /apps.hereandnowai.com/apps/${{ github.event.repository.name }}
        # Deploy public/data folder
        mkdir -p /apps.hereandnowai.com/data/
        mirror -R --delete --verbose ./public/data /apps.hereandnowai.com/data/
        bye
        FTP_EOF
