name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or your preferred Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy built files (dist) with FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-directory: ${{ secrets.FTP_REMOTE_PATH }}
        # No exclude needed here as we want to deploy all built files from dist

    - name: Deploy public/data with FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public/data/
        server-directory: ${{ secrets.FTP_REMOTE_PATH }}data/
        # No exclude needed here as we want to deploy all data files
